---
- name: reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: apt update
  ansible.builtin.apt:
    update_cache: true
