---
- name: restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: restart alertmanager
  ansible.builtin.service:
    name: prometheus-alertmanager
    state: restarted
